"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";

const FAQS: { q: string; a: string }[] = [
  {
    q: "Is this connected to a real bank or wallet provider?",
    a: "No. There's no real financial data anywhere in this project — the entire dataset (50 accounts, ~1,700 transactions) is generated by a synthetic-data script with a deliberate mix of normal behavior and injected anomalies (velocity bursts, amount spikes, geo jumps, new devices), clearly labeled and never shown to the agent.",
  },
  {
    q: "What actually makes this \"agentic\" rather than just an LLM call?",
    a: "The agent decides which check to run first based on its own hypothesis, then after each check decides whether it has enough evidence to stop or should investigate further — a real conditional loop in the LangGraph, not a fixed sequence. A pipeline that always runs every check and has an LLM summarize the result at the end isn't agentic, it's automation with narration.",
  },
  {
    q: "What is the \"episodic memory\" / precedent retrieval?",
    a: "Every completed investigation is embedded (OpenAI text-embedding-3-small) and stored in Postgres via pgvector. Before delivering a verdict, the agent searches for the closest similar past case and factors it in — so the system genuinely gets more context-aware over time, not just re-running static rules.",
  },
  {
    q: "Do I need to provide my own OpenAI key?",
    a: "Yes, by design (BYOK). Each investigation runs several GPT-4o calls, so rather than one shared key absorbing every visitor's usage, you paste your own key (stored only in your browser, sent directly with your request, never logged) — or use the rate-limited shared demo key if you'd rather not.",
  },
  {
    q: "What's the analyst \"Ops dashboard\" for?",
    a: "It's the human-in-the-loop piece: an analyst can review any completed investigation's full reasoning trail and confirm it as fraud or mark it a false positive. That feedback corrects the stored precedent, so a wrong verdict doesn't stay wrong forever in the agent's memory.",
  },
  {
    q: "Why can the accuracy numbers never hit 100%?",
    a: "The very first transaction in an injected velocity burst is genuinely indistinguishable from normal activity — there's no prior signal yet for the agent (or a human analyst) to catch. Recall is capped below 100% by the nature of the scenario, not by a weak model.",
  },
  {
    q: "Is this production-ready?",
    a: "No — it's a portfolio demonstration of the architecture (LangGraph, pgvector, Redis-backed caching/rate-limiting, WebSocket push, JWT analyst auth), not a certified fraud-prevention system.",
  },
];

export default function Faq() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section id="faq" className="max-w-3xl mx-auto px-4 sm:px-6 py-20">
      <div className="text-center mb-10">
        <div className="text-xs uppercase tracking-widest font-bold" style={{ color: "var(--accent)" }}>FAQ</div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-[var(--text-strong)] mt-2">Questions, answered</h2>
      </div>

      <div className="space-y-3">
        {FAQS.map((f, i) => {
          const isOpen = open === i;
          return (
            <div key={i} className="card rounded-2xl overflow-hidden">
              <button onClick={() => setOpen(isOpen ? null : i)}
                className="w-full flex items-center justify-between gap-4 p-5 text-left">
                <span className="font-semibold text-[var(--text-strong)]">{f.q}</span>
                <ChevronDown className={`w-5 h-5 shrink-0 text-[var(--text-faint)] transition-transform ${isOpen ? "rotate-180" : ""}`} />
              </button>
              <AnimatePresence initial={false}>
                {isOpen && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25 }}>
                    <p className="px-5 pb-5 text-sm text-[var(--text-muted)] leading-relaxed">{f.a}</p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>
    </section>
  );
}