import asyncio
import io
from functools import partial

from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from agents.state import DrugInteractionState
from core.logger import logger

_SEVERITY_COLORS: dict[str, str] = {
    "contraindicated": "#DC2626",
    "severe": "#EA580C",
    "moderate": "#CA8A04",
    "minor": "#16A34A",
    "none": "#6B7280",
    "unknown": "#9CA3AF",
}

_RISK_BADGE_COLORS: dict[str, str] = {
    "HIGH": "#DC2626",
    "MODERATE": "#D97706",
    "LOW": "#16A34A",
    "NONE": "#6B7280",
}


def _build_pdf_sync(state: DrugInteractionState) -> bytes:
    synthesis = state["synthesis"]
    patient = state["patient_profile"]
    drugs = state["drugs"]
    request_id = state["request_id"]
    pair_results: list[dict] = synthesis["sorted_results"]

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Title ────────────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=HexColor("#1E3A5F"),
        spaceAfter=4,
    )
    story.append(Paragraph("Drug Interaction Safety Report", title_style))

    sub_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=9, textColor=HexColor("#6B7280"))
    story.append(Paragraph(f"Request ID: {request_id}  |  Generated by Drug Interaction Checker AI", sub_style))
    story.append(Spacer(1, 0.2 * inch))

    # ── Patient profile ───────────────────────────────────────────────────────
    story.append(Paragraph("Patient Profile", styles["Heading2"]))
    patient_rows = [
        ["Age", str(patient.get("age", "N/A"))],
        ["Renal Impairment", "Yes" if patient.get("renal_impairment") else "No"],
        ["Hepatic Impairment", "Yes" if patient.get("hepatic_impairment") else "No"],
        ["Pregnant", "Yes" if patient.get("pregnant") else "No"],
        ["Active Conditions", ", ".join(patient.get("conditions", [])) or "None reported"],
    ]
    pt = Table(patient_rows, colWidths=[2 * inch, 4.5 * inch])
    pt.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), HexColor("#F3F4F6")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E5E7EB")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ]
        )
    )
    story.append(pt)
    story.append(Spacer(1, 0.15 * inch))

    # ── Medications ──────────────────────────────────────────────────────────
    story.append(Paragraph("Medications Analyzed", styles["Heading2"]))
    story.append(Paragraph(", ".join(d.title() for d in drugs), styles["Normal"]))
    story.append(Spacer(1, 0.12 * inch))

    # ── Overall risk badge ────────────────────────────────────────────────────
    risk = synthesis["overall_risk"]
    risk_color = _RISK_BADGE_COLORS.get(risk, "#6B7280")
    risk_style = ParagraphStyle(
        "Risk",
        parent=styles["Normal"],
        fontSize=13,
        textColor=HexColor(risk_color),
        fontName="Helvetica-Bold",
        spaceAfter=4,
    )
    story.append(Paragraph(f"Overall Risk: {risk} — {synthesis['risk_label']}", risk_style))
    story.append(Spacer(1, 0.1 * inch))

    # ── Clinical summary ──────────────────────────────────────────────────────
    story.append(Paragraph("Clinical Summary", styles["Heading2"]))
    story.append(Paragraph(synthesis["clinical_summary"], styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))

    # ── Interaction matrix table ──────────────────────────────────────────────
    story.append(Paragraph("Interaction Details", styles["Heading2"]))

    matrix_header = ["Drug A", "Drug B", "Severity", "Ev. Level", "Management"]
    matrix_rows = [matrix_header] + [
        [
            r["drug_a"].title(),
            r["drug_b"].title(),
            r["severity"].upper(),
            r["evidence_level"],
            (r["management"][:70] + "…") if len(r["management"]) > 70 else r["management"],
        ]
        for r in pair_results
    ]

    col_widths = [1.1 * inch, 1.1 * inch, 1.0 * inch, 0.7 * inch, 2.7 * inch]
    matrix = Table(matrix_rows, colWidths=col_widths)

    ts = [
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1E3A5F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E5E7EB")),
        ("PADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]

    # Colour-code severity cells
    for i, r in enumerate(pair_results, start=1):
        col = HexColor(_SEVERITY_COLORS.get(r.get("severity", "unknown"), "#9CA3AF"))
        ts += [
            ("BACKGROUND", (2, i), (2, i), col),
            ("TEXTCOLOR", (2, i), (2, i), white),
            ("FONTNAME", (2, i), (2, i), "Helvetica-Bold"),
        ]

    matrix.setStyle(TableStyle(ts))
    story.append(matrix)
    story.append(Spacer(1, 0.2 * inch))

    # ── Mechanism detail (per pair) ───────────────────────────────────────────
    story.append(Paragraph("Mechanism & Clinical Effects", styles["Heading2"]))
    for r in pair_results:
        heading = ParagraphStyle("PairHead", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=9)
        story.append(
            Paragraph(
                f"{r['drug_a'].title()} + {r['drug_b'].title()} [{r['severity'].upper()}]",
                heading,
            )
        )
        story.append(Paragraph(f"Mechanism: {r['mechanism']}", styles["Normal"]))
        story.append(Paragraph(f"Clinical effects: {r['clinical_effects']}", styles["Normal"]))
        if r.get("patient_adjustments"):
            story.append(Paragraph(f"Patient-specific: {r['patient_adjustments']}", styles["Normal"]))
        story.append(Spacer(1, 0.08 * inch))

    # ── Evidence references ───────────────────────────────────────────────────
    all_sources = [
        src
        for r in pair_results
        for src in r.get("evidence_sources", [])
        if src.get("pmid")
    ]
    seen_pmids: set[str] = set()
    unique_sources = [s for s in all_sources if not (s["pmid"] in seen_pmids or seen_pmids.add(s["pmid"]))]  # type: ignore[func-returns-value]

    if unique_sources:
        story.append(Paragraph("Evidence References (PubMed)", styles["Heading2"]))
        for src in unique_sources:
            story.append(Paragraph(f"• PMID {src['pmid']} — {src['url']}", styles["Normal"]))
        story.append(Spacer(1, 0.15 * inch))

    # ── Disclaimer ────────────────────────────────────────────────────────────
    disc_style = ParagraphStyle(
        "Disc",
        parent=styles["Normal"],
        fontSize=7.5,
        textColor=HexColor("#9CA3AF"),
        borderPad=4,
    )
    story.append(
        Paragraph(
            "DISCLAIMER: This report is AI-generated for educational and decision-support purposes only. "
            "It does not constitute medical advice. Always verify interactions with a current drug reference "
            "(e.g., Lexicomp, Micromedex) and consult a licensed healthcare professional before making any "
            "clinical decision.",
            disc_style,
        )
    )

    doc.build(story)
    return buffer.getvalue()


async def generate_pdf_report(state: DrugInteractionState) -> dict:
    """Run synchronous ReportLab in a thread executor to avoid blocking the event loop."""
    loop = asyncio.get_event_loop()
    pdf_bytes: bytes = await loop.run_in_executor(None, partial(_build_pdf_sync, state))

    logger.info(f"PDF generated | req={state['request_id']} | size={len(pdf_bytes) // 1024}KB")

    return {"pdf_bytes": pdf_bytes}